# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-24 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='campus_name',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
